disabled_rules:
  - closure_parameter_position
  - identifier_name
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - first_where
  - flatmap_over_map_reduce
  - indentation_width
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition
excluded:
  - .build
  - .swiftpm
indentation_width:
  include_comments: false
  include_compiler_directives: false
line_length:
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true
nesting:
  type_level: 3
  function_level: 4
function_body_length:
  warning: 100
type_body_length:
  warning: 300
  error: 400
cyclomatic_complexity:
  ignores_case_statements: true
indentation: tabs
